---
- name: Deploy PHP Application and LAMP Stack
  hosts: slave
  become: yes
  tasks:
    - name: Copy the PHP application deployment script
      copy:
        src: /home/vagrant/LAMP.sh
        dest: /tmp/script.sh
        mode: '0755'

    - name: Execute the deployment script
      command: /tmp/script.sh
      become: yes

    - name: Set VM_IP variable
      set_fact:
        VM_IP: "192.168.56.6"

    - name: Verify Laravel application accessibility
      uri:
        url: "http://{{ VM_IP }}"
        status_code: 200
      register: app_access

    - name: Fail if Laravel application is not accessible
      fail:
        msg: "Laravel application is not accessible through the VM's IP address."
      when: app_access.status != 200

    - name: Update Laravel Application Timezone
      lineinfile:
        path: /var/www/html/laravel/config/app.php
        regexp: '^\s*"timezone" => (.*)'
        line: '    "timezone" => "Africa/Lagos",'

    - name: Add a cron job to check server uptime
      cron:
        name: "Check Server Uptime"
        job: "0 0 * * * uptime > /home/vagrant/uptime.log"
        user: vagrant